name: CD Maven
on:
  registry_package: 
    types: [ "published" ]
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  test:
    name: Maven Test
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write 
    steps:
     - uses: actions/checkout@v4
     - uses: actions/setup-java@v3
       with:
        java-version: '11'
        distribution: 'temurin'
     - name: Maven commands
       run: mvn install
     - run: mvn verify
     - name: Condition Package
       if: ${{ job.status }} == success
       run: mvn clean install
     - run: pwd
     - run: ls -l
     - run: mvn deploy -Dregistry=https://maven.pkg.github.com/FCJG/TestSPS23 -Dtoken=$GITHUB_TOKEN --file ./pom.xml
       env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
