name: CD Maven
on:
  registry_package: 
    types: [ "published" ]
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  test:
    name: Maven Test
    runs-on: ubuntu-latest
    container: maven:3.9.4-eclipse-temurin-17-alpine
    permissions: 
      contents: read
      packages: write 
    steps:
     - name: Check out repository code
       uses: actions/checkout@v2
     - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
     - name: Maven commands
       run: mvn install
     - run: mvn verify
     - name: Condition Package
       if: ${{ job.status }} == success
       env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
       run: mvn install
     - run: mvn deploy -Dregistry=https://maven.pkg.github.com/JohannSansores/TestSPS23
