name: Java CI with Maven
on:
  pull_request:
    branches: [ "master" ]
  commit:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: ./mvnw verify
